FROM mysql:5.7

ENV MYSQL_DATABASE=cardcardsone \
    MYSQL_USER=cardcardsone \
    MYSQL_PASSWORD=cardcardsone \
    MYSQL_ROOT_PASSWORD=cardcardsone


EXPOSE 3306

COPY ./env/mysql/my.cnf /etc/mysql/my.cnf